#!/usr/bin/env python3
"""Add 15 new FAQs to all 7 locale files. Existing 10 are kept."""
import json
from pathlib import Path

ROOT = Path('/Users/md/silkincom_claude')

# 15 new FAQs in 7 languages (heritage 5, materials 5, sizing 3, services 2)
NEW_FAQS = {
    'it': [
        # Heritage (5)
        {'q': 'Da quanto tempo Como è capitale della seta?',
         'a': 'Como è il distretto serico più importante d\'Europa dal XV secolo. Già nel 1400 esistevano filande comasche; oggi la zona produce oltre il 70% della seta italiana e ospita le più prestigiose maison del lusso mondiale.'},
        {'q': 'Chi è il fondatore di SILKinCOM?',
         'a': 'SILKinCOM è stata fondata da Marco Dibenedetto, con sede operativa a Cermenate (Como). La maison nasce per portare l\'eredità tessile comasca direttamente al consumatore finale, senza intermediari.'},
        {'q': 'Cosa significa "Made in Como"?',
         'a': 'Made in Como significa che ogni passaggio — dalla filatura alla tessitura alla stampa alla rifinitura — avviene fisicamente nel distretto serico comasco. Non è una semplice etichetta: è una filiera corta interamente locale.'},
        {'q': 'Lavorate con artigiani indipendenti?',
         'a': 'Sì. Collaboriamo con tessitori, stampatori e rifinitori indipendenti del distretto comasco, molti dei quali tramandano il mestiere da generazioni. Ogni capo porta la firma del laboratorio che lo ha realizzato.'},
        {'q': 'Avete uno showroom o atelier visitabile?',
         'a': 'Il nostro atelier si trova a Cermenate (Como). Le visite sono su appuntamento, contattaci via email per organizzare un appuntamento personalizzato con la nostra responsabile customer experience.'},
        # Materials (5)
        {'q': 'Da dove proviene il vostro cashmere?',
         'a': 'Il nostro cashmere proviene dalle regioni più fredde dell\'Asia centrale (Mongolia interna), dove la fibra è più fine (14-16 micron) per via del clima rigido. Selezioniamo solo il vello sotto-collo, raccolto a mano.'},
        {'q': 'La vostra seta è davvero italiana?',
         'a': 'Sì. La seta è filata, tessuta e finita nel distretto comasco. Il bozzolo grezzo arriva principalmente dalla Cina (l\'Italia non produce più seta grezza dal dopoguerra), ma tutta la trasformazione tessile è italiana.'},
        {'q': 'Cosa rende il twill di seta speciale?',
         'a': 'Il twill è un\'armatura tessile che crea una diagonale visibile sul tessuto. Il twill di seta comasco è celebre per il suo peso (60-65g/m²), la mano fluida e la stabilità del colore — ideale per foulard di lusso.'},
        {'q': 'Cos\'è il cotone a fibra extra-lunga?',
         'a': 'Il cotone a fibra extra-lunga (oltre 35mm) è la categoria più pregiata: produce filati più fini, resistenti e con maggior brillantezza rispetto al cotone standard. Lo selezioniamo da coltivazioni mediterranee ed egiziane.'},
        {'q': 'I vostri tessuti sono certificati?',
         'a': 'Lavoriamo con fornitori certificati OEKO-TEX Standard 100, che garantisce l\'assenza di sostanze nocive nei tessuti finiti. Per la seta comasca seguiamo gli standard del distretto Seri.co.'},
        # Sizing (3)
        {'q': 'Quali sono le misure standard di una sciarpa SILKinCOM?',
         'a': 'Sciarpa lunga: 180×45 cm. Pashmina: 200×70 cm. Stola: 200×100 cm. Foulard quadrato (carré): 90×90 cm. Twilly: 85×5 cm. Ogni scheda prodotto specifica le dimensioni esatte.'},
        {'q': 'Le sciarpe accorciano dopo il lavaggio?',
         'a': 'No, se segui le istruzioni di lavaggio. Cashmere e seta possono perdere 1-2% di stabilità dimensionale al primo lavaggio: rispetta sempre temperature fredde e detergenti specifici per evitare ritiri.'},
        {'q': 'Come scelgo la dimensione giusta come regalo?',
         'a': 'Per un regalo classico consigliamo la sciarpa lunga 180×45 cm: misura versatile, adatta a uomini e donne. Per un dono più ricercato, la pashmina 200×70 cm è scelta sicura per chi ama avvolgersi nel calore.'},
        # Services (2)
        {'q': 'Realizzate prodotti su misura?',
         'a': 'Sì. Il nostro servizio Atelier permette di personalizzare colori, dimensioni e finiture. I tempi di realizzazione sono 4-6 settimane. Visita la pagina Atelier per dettagli e prezzi.'},
        {'q': 'Vendete a hotel, ristoranti o aziende?',
         'a': 'Sì. Abbiamo un canale dedicato hospitality e corporate gifting con condizioni speciali per ordini superiori a 20 pezzi. Contattaci via email per richiedere il listino B2B.'},
    ],
    'en': [
        {'q': 'How long has Como been the silk capital?',
         'a': 'Como has been Europe\'s leading silk district since the 15th century. Como mills existed as early as 1400; today the area produces over 70% of Italian silk and hosts the world\'s most prestigious luxury maisons.'},
        {'q': 'Who founded SILKinCOM?',
         'a': 'SILKinCOM was founded by Marco Dibenedetto, with operations based in Cermenate (Como). The maison was born to bring Como\'s textile heritage directly to the final customer, without intermediaries.'},
        {'q': 'What does "Made in Como" mean?',
         'a': 'Made in Como means every step — from spinning to weaving to printing to finishing — happens physically within the Como silk district. It is not just a label: it is a fully local supply chain.'},
        {'q': 'Do you work with independent artisans?',
         'a': 'Yes. We collaborate with independent weavers, printers and finishers in the Como district, many of whom pass the craft down through generations. Every piece bears the mark of the workshop that made it.'},
        {'q': 'Do you have a showroom or visitable atelier?',
         'a': 'Our atelier is in Cermenate (Como). Visits are by appointment — contact us by email to schedule a personalised meeting with our customer experience manager.'},
        {'q': 'Where does your cashmere come from?',
         'a': 'Our cashmere comes from the coldest regions of Central Asia (Inner Mongolia), where the fiber is finest (14-16 microns) due to the harsh climate. We select only the under-neck fleece, harvested by hand.'},
        {'q': 'Is your silk really Italian?',
         'a': 'Yes. The silk is spun, woven and finished in the Como district. Raw cocoons come mainly from China (Italy no longer produces raw silk since WWII), but all textile transformation is Italian.'},
        {'q': 'What makes silk twill special?',
         'a': 'Twill is a weave structure creating a visible diagonal on the fabric. Como silk twill is renowned for its weight (60-65g/m²), fluid hand and color stability — ideal for luxury scarves.'},
        {'q': 'What is extra-long staple cotton?',
         'a': 'Extra-long staple cotton (over 35mm fiber) is the most prized category: it produces finer, stronger and more lustrous yarns than standard cotton. We source it from Mediterranean and Egyptian growers.'},
        {'q': 'Are your fabrics certified?',
         'a': 'We work with OEKO-TEX Standard 100 certified suppliers, guaranteeing no harmful substances in finished fabrics. For Como silk we follow the Seri.co district standards.'},
        {'q': 'What are SILKinCOM\'s standard scarf sizes?',
         'a': 'Long scarf: 180×45 cm. Pashmina: 200×70 cm. Stole: 200×100 cm. Square scarf (carré): 90×90 cm. Twilly: 85×5 cm. Each product page specifies exact dimensions.'},
        {'q': 'Do scarves shrink after washing?',
         'a': 'No, if you follow the washing instructions. Cashmere and silk may lose 1-2% dimensional stability at first wash: always respect cold temperatures and specific detergents to avoid shrinkage.'},
        {'q': 'How do I choose the right size as a gift?',
         'a': 'For a classic gift we recommend the long scarf 180×45 cm: versatile size, suitable for men and women. For a more refined gift, the 200×70 cm pashmina is a safe choice for those who love to wrap in warmth.'},
        {'q': 'Do you make custom pieces?',
         'a': 'Yes. Our Atelier service allows customisation of colours, sizes and finishes. Production time is 4-6 weeks. Visit the Atelier page for details and pricing.'},
        {'q': 'Do you sell to hotels, restaurants or businesses?',
         'a': 'Yes. We have a dedicated hospitality and corporate gifting channel with special terms for orders over 20 pieces. Contact us by email to request the B2B price list.'},
    ],
    'es': [
        {'q': '¿Desde cuándo Como es la capital de la seda?',
         'a': 'Como es el distrito de la seda más importante de Europa desde el siglo XV. Ya en 1400 existían hilanderías comascas; hoy la zona produce más del 70% de la seda italiana y alberga las maisons de lujo más prestigiosas del mundo.'},
        {'q': '¿Quién es el fundador de SILKinCOM?',
         'a': 'SILKinCOM fue fundada por Marco Dibenedetto, con sede operativa en Cermenate (Como). La maison nace para llevar la herencia textil comasca directamente al consumidor final, sin intermediarios.'},
        {'q': '¿Qué significa "Made in Como"?',
         'a': 'Made in Como significa que cada paso — del hilado al tejido a la estampación a la finalización — ocurre físicamente en el distrito comasco. No es una simple etiqueta: es una cadena de suministro corta totalmente local.'},
        {'q': '¿Trabajáis con artesanos independientes?',
         'a': 'Sí. Colaboramos con tejedores, estampadores y artesanos independientes del distrito comasco, muchos de los cuales transmiten el oficio durante generaciones. Cada pieza lleva la firma del taller que la realizó.'},
        {'q': '¿Tenéis un showroom o atelier visitable?',
         'a': 'Nuestro atelier está en Cermenate (Como). Las visitas son con cita previa, contáctanos por email para organizar una cita personalizada con nuestra responsable de customer experience.'},
        {'q': '¿De dónde proviene vuestro cashmere?',
         'a': 'Nuestro cashmere proviene de las regiones más frías de Asia Central (Mongolia Interior), donde la fibra es más fina (14-16 micras) por el clima riguroso. Seleccionamos solo el vellón del cuello, recolectado a mano.'},
        {'q': '¿Vuestra seda es realmente italiana?',
         'a': 'Sí. La seda se hila, teje y termina en el distrito comasco. El capullo crudo llega principalmente de China (Italia ya no produce seda cruda desde la posguerra), pero toda la transformación textil es italiana.'},
        {'q': '¿Qué hace especial al twill de seda?',
         'a': 'El twill es una estructura de tejido que crea una diagonal visible. El twill de seda comasco es célebre por su peso (60-65g/m²), su tacto fluido y la estabilidad del color — ideal para foulards de lujo.'},
        {'q': '¿Qué es el algodón de fibra extra larga?',
         'a': 'El algodón de fibra extra larga (más de 35mm) es la categoría más preciada: produce hilados más finos, resistentes y con mayor brillo. Lo seleccionamos de cultivos mediterráneos y egipcios.'},
        {'q': '¿Vuestros tejidos están certificados?',
         'a': 'Trabajamos con proveedores certificados OEKO-TEX Standard 100, que garantiza la ausencia de sustancias nocivas en los tejidos. Para la seda comasca seguimos los estándares del distrito Seri.co.'},
        {'q': '¿Cuáles son las medidas estándar de una bufanda SILKinCOM?',
         'a': 'Bufanda larga: 180×45 cm. Pashmina: 200×70 cm. Estola: 200×100 cm. Foulard cuadrado (carré): 90×90 cm. Twilly: 85×5 cm. Cada ficha de producto especifica las dimensiones exactas.'},
        {'q': '¿Las bufandas encogen tras el lavado?',
         'a': 'No, si sigues las instrucciones de lavado. Cashmere y seda pueden perder 1-2% de estabilidad dimensional en el primer lavado: respeta siempre temperaturas frías y detergentes específicos.'},
        {'q': '¿Cómo elijo la talla adecuada como regalo?',
         'a': 'Para un regalo clásico recomendamos la bufanda larga 180×45 cm: medida versátil, apta para hombres y mujeres. Para un regalo más refinado, la pashmina 200×70 cm es una elección segura.'},
        {'q': '¿Realizáis productos a medida?',
         'a': 'Sí. Nuestro servicio Atelier permite personalizar colores, dimensiones y acabados. Los tiempos de realización son de 4-6 semanas. Visita la página Atelier para detalles y precios.'},
        {'q': '¿Vendéis a hoteles, restaurantes o empresas?',
         'a': 'Sí. Tenemos un canal dedicado a hospitality y corporate gifting con condiciones especiales para pedidos superiores a 20 piezas. Contáctanos por email para solicitar la lista B2B.'},
    ],
    'fr': [
        {'q': 'Depuis quand Côme est-elle la capitale de la soie ?',
         'a': 'Côme est le district séricicole le plus important d\'Europe depuis le XVe siècle. Dès 1400 des filatures comasques existaient ; aujourd\'hui la zone produit plus de 70% de la soie italienne et accueille les plus prestigieuses maisons de luxe au monde.'},
        {'q': 'Qui est le fondateur de SILKinCOM ?',
         'a': 'SILKinCOM a été fondée par Marco Dibenedetto, avec son siège opérationnel à Cermenate (Côme). La maison est née pour porter l\'héritage textile comasque directement au consommateur final, sans intermédiaires.'},
        {'q': 'Que signifie "Made in Como" ?',
         'a': 'Made in Como signifie que chaque étape — du filage au tissage à l\'impression à la finition — a lieu physiquement dans le district comasque. Ce n\'est pas une simple étiquette : c\'est une chaîne d\'approvisionnement courte entièrement locale.'},
        {'q': 'Travaillez-vous avec des artisans indépendants ?',
         'a': 'Oui. Nous collaborons avec des tisserands, imprimeurs et finisseurs indépendants du district comasque, dont beaucoup transmettent le métier depuis des générations. Chaque pièce porte la signature de l\'atelier qui l\'a réalisée.'},
        {'q': 'Avez-vous un showroom ou un atelier visitable ?',
         'a': 'Notre atelier se trouve à Cermenate (Côme). Les visites se font sur rendez-vous, contactez-nous par email pour organiser un rendez-vous personnalisé avec notre responsable customer experience.'},
        {'q': 'D\'où vient votre cachemire ?',
         'a': 'Notre cachemire provient des régions les plus froides d\'Asie centrale (Mongolie intérieure), où la fibre est la plus fine (14-16 microns) en raison du climat rigoureux. Nous sélectionnons uniquement la toison du cou, récoltée à la main.'},
        {'q': 'Votre soie est-elle vraiment italienne ?',
         'a': 'Oui. La soie est filée, tissée et finie dans le district comasque. Le cocon brut vient principalement de Chine (l\'Italie ne produit plus de soie brute depuis l\'après-guerre), mais toute la transformation textile est italienne.'},
        {'q': 'Qu\'est-ce qui rend le twill de soie spécial ?',
         'a': 'Le twill est une armure textile qui crée une diagonale visible. Le twill de soie comasque est célèbre pour son poids (60-65g/m²), sa main fluide et la stabilité de la couleur — idéal pour foulards de luxe.'},
        {'q': 'Qu\'est-ce que le coton à fibres extra-longues ?',
         'a': 'Le coton à fibres extra-longues (plus de 35mm) est la catégorie la plus prisée : il produit des fils plus fins, résistants et plus brillants. Nous le sélectionnons auprès de cultures méditerranéennes et égyptiennes.'},
        {'q': 'Vos tissus sont-ils certifiés ?',
         'a': 'Nous travaillons avec des fournisseurs certifiés OEKO-TEX Standard 100, garantissant l\'absence de substances nocives. Pour la soie comasque nous suivons les standards du district Seri.co.'},
        {'q': 'Quelles sont les dimensions standard d\'une écharpe SILKinCOM ?',
         'a': 'Écharpe longue : 180×45 cm. Pashmina : 200×70 cm. Étole : 200×100 cm. Foulard carré : 90×90 cm. Twilly : 85×5 cm. Chaque fiche produit précise les dimensions exactes.'},
        {'q': 'Les écharpes rétrécissent-elles après lavage ?',
         'a': 'Non, si vous suivez les instructions de lavage. Cachemire et soie peuvent perdre 1-2% de stabilité dimensionnelle au premier lavage : respectez toujours températures froides et détergents spécifiques.'},
        {'q': 'Comment choisir la bonne taille comme cadeau ?',
         'a': 'Pour un cadeau classique nous recommandons l\'écharpe longue 180×45 cm : taille polyvalente, adaptée aux hommes et aux femmes. Pour un cadeau plus raffiné, la pashmina 200×70 cm est un choix sûr.'},
        {'q': 'Réalisez-vous des pièces sur mesure ?',
         'a': 'Oui. Notre service Atelier permet de personnaliser couleurs, dimensions et finitions. Les délais de réalisation sont de 4-6 semaines. Visitez la page Atelier pour détails et prix.'},
        {'q': 'Vendez-vous aux hôtels, restaurants ou entreprises ?',
         'a': 'Oui. Nous avons un canal dédié hospitality et corporate gifting avec conditions spéciales pour commandes supérieures à 20 pièces. Contactez-nous par email pour la liste de prix B2B.'},
    ],
    'de': [
        {'q': 'Seit wann ist Como die Hauptstadt der Seide?',
         'a': 'Como ist seit dem 15. Jahrhundert das wichtigste Seidendistrikt Europas. Bereits 1400 existierten Comasker Spinnereien; heute produziert die Region über 70% der italienischen Seide und beheimatet die prestigeträchtigsten Luxusmaisons der Welt.'},
        {'q': 'Wer ist der Gründer von SILKinCOM?',
         'a': 'SILKinCOM wurde von Marco Dibenedetto gegründet, mit Sitz in Cermenate (Como). Die Maison entstand, um das Comasker Textilerbe direkt zum Endverbraucher zu bringen, ohne Zwischenhändler.'},
        {'q': 'Was bedeutet "Made in Como"?',
         'a': 'Made in Como bedeutet, dass jeder Schritt — vom Spinnen zum Weben zum Druck zur Veredelung — physisch im Comasker Bezirk stattfindet. Es ist kein bloßes Etikett: Es ist eine vollständig lokale Lieferkette.'},
        {'q': 'Arbeiten Sie mit unabhängigen Handwerkern?',
         'a': 'Ja. Wir kollaborieren mit unabhängigen Webern, Druckern und Veredlern aus dem Comasker Distrikt, von denen viele das Handwerk über Generationen weitergeben. Jedes Stück trägt die Signatur der Werkstatt, die es geschaffen hat.'},
        {'q': 'Haben Sie einen Showroom oder besuchbares Atelier?',
         'a': 'Unser Atelier befindet sich in Cermenate (Como). Besuche nach Terminvereinbarung, kontaktieren Sie uns per E-Mail für einen persönlichen Termin mit unserer Customer-Experience-Managerin.'},
        {'q': 'Woher kommt Ihr Kaschmir?',
         'a': 'Unser Kaschmir stammt aus den kältesten Regionen Zentralasiens (Innere Mongolei), wo die Faser am feinsten ist (14-16 Mikron) aufgrund des rauen Klimas. Wir wählen nur das Halsvlies, von Hand gesammelt.'},
        {'q': 'Ist Ihre Seide wirklich italienisch?',
         'a': 'Ja. Die Seide wird im Comasker Distrikt gesponnen, gewebt und veredelt. Rohe Kokons kommen hauptsächlich aus China (Italien produziert seit der Nachkriegszeit keine Rohseide mehr), aber die gesamte Textilverarbeitung ist italienisch.'},
        {'q': 'Was macht Seiden-Twill besonders?',
         'a': 'Twill ist eine Webstruktur, die eine sichtbare Diagonale erzeugt. Comasker Seiden-Twill ist berühmt für sein Gewicht (60-65g/m²), seinen fließenden Griff und seine Farbstabilität — ideal für Luxusschals.'},
        {'q': 'Was ist extra-langstapelige Baumwolle?',
         'a': 'Extra-langstapelige Baumwolle (über 35mm) ist die wertvollste Kategorie: Sie produziert feinere, stärkere und glänzendere Garne. Wir beziehen sie aus mediterranen und ägyptischen Anbaugebieten.'},
        {'q': 'Sind Ihre Stoffe zertifiziert?',
         'a': 'Wir arbeiten mit OEKO-TEX Standard 100 zertifizierten Lieferanten, was die Abwesenheit schädlicher Substanzen garantiert. Für Comasker Seide folgen wir den Standards des Seri.co-Distrikts.'},
        {'q': 'Was sind die Standardmaße eines SILKinCOM-Schals?',
         'a': 'Langer Schal: 180×45 cm. Pashmina: 200×70 cm. Stola: 200×100 cm. Quadratischer Foulard (Carré): 90×90 cm. Twilly: 85×5 cm. Jede Produktseite spezifiziert die genauen Maße.'},
        {'q': 'Laufen Schals nach dem Waschen ein?',
         'a': 'Nein, wenn Sie die Waschanleitung befolgen. Kaschmir und Seide können beim ersten Waschen 1-2% Maßhaltigkeit verlieren: Beachten Sie stets kalte Temperaturen und spezifische Waschmittel.'},
        {'q': 'Wie wähle ich die richtige Größe als Geschenk?',
         'a': 'Für ein klassisches Geschenk empfehlen wir den langen Schal 180×45 cm: vielseitige Größe, für Männer und Frauen geeignet. Für ein raffinierteres Geschenk ist die 200×70 cm Pashmina eine sichere Wahl.'},
        {'q': 'Stellen Sie Maßanfertigungen her?',
         'a': 'Ja. Unser Atelier-Service ermöglicht die Personalisierung von Farben, Größen und Verarbeitungen. Die Fertigungszeit beträgt 4-6 Wochen. Besuchen Sie die Atelier-Seite für Details und Preise.'},
        {'q': 'Verkaufen Sie an Hotels, Restaurants oder Unternehmen?',
         'a': 'Ja. Wir haben einen dedizierten Hospitality- und Corporate-Gifting-Kanal mit besonderen Konditionen für Bestellungen über 20 Stück. Kontaktieren Sie uns per E-Mail für die B2B-Preisliste.'},
    ],
    'pt': [
        {'q': 'Há quanto tempo Como é a capital da seda?',
         'a': 'Como é o distrito sericícola mais importante da Europa desde o século XV. Já em 1400 existiam fiandeiras comascas; hoje a zona produz mais de 70% da seda italiana e acolhe as mais prestigiosas maisons de luxo do mundo.'},
        {'q': 'Quem é o fundador da SILKinCOM?',
         'a': 'A SILKinCOM foi fundada por Marco Dibenedetto, com sede operacional em Cermenate (Como). A maison nasceu para levar a herança têxtil comasca diretamente ao consumidor final, sem intermediários.'},
        {'q': 'O que significa "Made in Como"?',
         'a': 'Made in Como significa que cada passo — da fiação à tecelagem à estampagem ao acabamento — acontece fisicamente no distrito comasco. Não é apenas um rótulo: é uma cadeia de abastecimento curta totalmente local.'},
        {'q': 'Trabalham com artesãos independentes?',
         'a': 'Sim. Colaboramos com tecelões, estampadores e finalizadores independentes do distrito comasco, muitos dos quais transmitem o ofício há gerações. Cada peça leva a assinatura do atelier que a realizou.'},
        {'q': 'Têm um showroom ou atelier visitável?',
         'a': 'O nosso atelier fica em Cermenate (Como). As visitas são com marcação prévia, contacte-nos por email para organizar uma visita personalizada com a nossa responsável de customer experience.'},
        {'q': 'De onde vem a vossa cashmere?',
         'a': 'A nossa cashmere vem das regiões mais frias da Ásia Central (Mongólia Interior), onde a fibra é mais fina (14-16 micros) devido ao clima rigoroso. Selecionamos apenas o velo do pescoço, colhido à mão.'},
        {'q': 'A vossa seda é realmente italiana?',
         'a': 'Sim. A seda é fiada, tecida e acabada no distrito comasco. O casulo bruto vem principalmente da China (a Itália já não produz seda crua desde o pós-guerra), mas toda a transformação têxtil é italiana.'},
        {'q': 'O que torna o twill de seda especial?',
         'a': 'O twill é uma armadura têxtil que cria uma diagonal visível. O twill de seda comasco é célebre pelo seu peso (60-65g/m²), o toque fluido e a estabilidade da cor — ideal para foulards de luxo.'},
        {'q': 'O que é o algodão de fibra extra longa?',
         'a': 'O algodão de fibra extra longa (mais de 35mm) é a categoria mais valorizada: produz fios mais finos, resistentes e brilhantes. Selecionamo-lo em culturas mediterrânicas e egípcias.'},
        {'q': 'Os vossos tecidos são certificados?',
         'a': 'Trabalhamos com fornecedores certificados OEKO-TEX Standard 100, garantindo a ausência de substâncias nocivas. Para a seda comasca seguimos os padrões do distrito Seri.co.'},
        {'q': 'Quais são as medidas standard de um cachecol SILKinCOM?',
         'a': 'Cachecol comprido: 180×45 cm. Pashmina: 200×70 cm. Estola: 200×100 cm. Foulard quadrado (carré): 90×90 cm. Twilly: 85×5 cm. Cada ficha de produto especifica as dimensões exatas.'},
        {'q': 'Os cachecóis encolhem após a lavagem?',
         'a': 'Não, se seguir as instruções de lavagem. Cashmere e seda podem perder 1-2% de estabilidade dimensional na primeira lavagem: respeite sempre temperaturas frias e detergentes específicos.'},
        {'q': 'Como escolho o tamanho certo como prenda?',
         'a': 'Para uma prenda clássica recomendamos o cachecol comprido 180×45 cm: medida versátil, adequada para homens e mulheres. Para uma prenda mais refinada, a pashmina 200×70 cm é uma escolha segura.'},
        {'q': 'Realizam produtos por medida?',
         'a': 'Sim. O nosso serviço Atelier permite personalizar cores, dimensões e acabamentos. Os tempos de realização são de 4-6 semanas. Visite a página Atelier para detalhes e preços.'},
        {'q': 'Vendem a hotéis, restaurantes ou empresas?',
         'a': 'Sim. Temos um canal dedicado a hospitality e corporate gifting com condições especiais para encomendas superiores a 20 peças. Contacte-nos por email para a lista de preços B2B.'},
    ],
    'nl': [
        {'q': 'Hoe lang is Como al de hoofdstad van zijde?',
         'a': 'Como is sinds de 15e eeuw het belangrijkste zijdedistrict van Europa. Al in 1400 bestonden Comasker spinnerijen; vandaag produceert het gebied meer dan 70% van de Italiaanse zijde en herbergt het de meest prestigieuze luxe maisons ter wereld.'},
        {'q': 'Wie is de oprichter van SILKinCOM?',
         'a': 'SILKinCOM is opgericht door Marco Dibenedetto, met operationele zetel in Cermenate (Como). De maison ontstond om Como\'s textielerfgoed rechtstreeks naar de eindklant te brengen, zonder tussenpersonen.'},
        {'q': 'Wat betekent "Made in Como"?',
         'a': 'Made in Como betekent dat elke stap — van spinnen tot weven tot bedrukken tot afwerking — fysiek plaatsvindt in het Comasker district. Het is geen simpel etiket: het is een volledig lokale toeleveringsketen.'},
        {'q': 'Werken jullie met onafhankelijke ambachtslieden?',
         'a': 'Ja. We werken samen met onafhankelijke wevers, drukkers en afwerkers uit het Comasker district, van wie velen het vak generaties lang doorgeven. Elk stuk draagt de signatuur van het atelier dat het heeft gemaakt.'},
        {'q': 'Hebben jullie een showroom of bezoekbaar atelier?',
         'a': 'Ons atelier bevindt zich in Cermenate (Como). Bezoeken zijn op afspraak, neem contact met ons op via email voor een gepersonaliseerde afspraak met onze customer experience manager.'},
        {'q': 'Waar komt jullie cashmere vandaan?',
         'a': 'Onze cashmere komt uit de koudste regio\'s van Centraal-Azië (Binnen-Mongolië), waar de vezel het fijnst is (14-16 micron) door het barre klimaat. We selecteren alleen de halsvacht, met de hand verzameld.'},
        {'q': 'Is jullie zijde echt Italiaans?',
         'a': 'Ja. De zijde wordt gesponnen, geweven en afgewerkt in het Comasker district. De ruwe cocon komt voornamelijk uit China (Italië produceert sinds de naoorlogse tijd geen ruwe zijde meer), maar alle textielverwerking is Italiaans.'},
        {'q': 'Wat maakt zijden twill speciaal?',
         'a': 'Twill is een weefstructuur die een zichtbare diagonaal creëert. Comasker zijden twill staat bekend om zijn gewicht (60-65g/m²), vloeiende greep en kleurstabiliteit — ideaal voor luxe foulards.'},
        {'q': 'Wat is extra-lange staple katoen?',
         'a': 'Extra-lange staple katoen (meer dan 35mm) is de meest gewaardeerde categorie: het produceert fijnere, sterkere en glanzendere garens. We selecteren het van mediterrane en Egyptische telers.'},
        {'q': 'Zijn jullie stoffen gecertificeerd?',
         'a': 'We werken met OEKO-TEX Standard 100 gecertificeerde leveranciers, wat de afwezigheid van schadelijke stoffen garandeert. Voor Comasker zijde volgen we de Seri.co-districtsstandaarden.'},
        {'q': 'Wat zijn de standaardmaten van een SILKinCOM-sjaal?',
         'a': 'Lange sjaal: 180×45 cm. Pashmina: 200×70 cm. Stola: 200×100 cm. Vierkante foulard (carré): 90×90 cm. Twilly: 85×5 cm. Elke productpagina specificeert de exacte afmetingen.'},
        {'q': 'Krimpen sjaals na het wassen?',
         'a': 'Nee, als je de wasinstructies volgt. Cashmere en zijde kunnen bij de eerste wasbeurt 1-2% maatvastheid verliezen: respecteer altijd koude temperaturen en specifieke wasmiddelen.'},
        {'q': 'Hoe kies ik de juiste maat als cadeau?',
         'a': 'Voor een klassiek cadeau raden we de lange sjaal 180×45 cm aan: veelzijdige maat, geschikt voor mannen en vrouwen. Voor een verfijnder cadeau is de 200×70 cm pashmina een veilige keuze.'},
        {'q': 'Maken jullie maatwerk producten?',
         'a': 'Ja. Onze Atelier-service maakt het mogelijk kleuren, afmetingen en afwerkingen te personaliseren. De productietijd bedraagt 4-6 weken. Bezoek de Atelier-pagina voor details en prijzen.'},
        {'q': 'Verkopen jullie aan hotels, restaurants of bedrijven?',
         'a': 'Ja. We hebben een dedicated hospitality en corporate gifting kanaal met speciale voorwaarden voor bestellingen boven 20 stuks. Neem contact met ons op via email voor de B2B-prijslijst.'},
    ],
}


def main():
    for lang, faqs in NEW_FAQS.items():
        path = ROOT / 'messages' / f'{lang}.json'
        with open(path, encoding='utf-8') as f:
            data = json.load(f)
        existing = data.get('faq', {}).get('faqs', [])
        # Append new faqs to existing
        combined = list(existing) + list(faqs)
        data.setdefault('faq', {})['faqs'] = combined
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f'{lang}: {len(existing)} -> {len(combined)} FAQs')


if __name__ == '__main__':
    main()
